[sources.journald]
beta = true
delivery_guarantee = "best_effort"
guides = []
output_types = ["log"]
resources = []
through_description = "log records from journald"

[sources.journald.fields.host]
type = "string"
examples = ["my.host.com"]
optional = false
description = """\
The value of the journald `_HOSTNAME` field.\
"""

[sources.journald.fields.message]
type = "string"
examples = ["Started GET / for 127.0.0.1 at 2012-03-10 14:28:14 +0100"]
optional = false
description = """\
The value of the journald `MESSAGE` field.\
"""

[sources.journald.fields.timestamp]
type = "timestamp"
examples = ["2019-11-01T21:15:47.443232Z"]
optional = false
description = """\
The value of the journald `_SOURCE_REALTIME_TIMESTAMP` field.\
"""

[sources.journald.options.current_runtime_only]
type = "bool"
null = true
default = true
description = "Include only entries from the current runtime (boot)"

[sources.journald.options.data_dir]
type = "string"
examples = ["/var/lib/vector"]
null = true
description = """\
The directory used to persist the journal checkpoint position. By \
default, the global `data_dir` is used. Please make sure the Vector \
project has write permissions to this dir. \
"""

[sources.journald.options.local_only]
type = "bool"
null = true
default = true
description = "Include only entries from the local system"

[sources.journald.options.units]
type = "[string]"
null = true
default = []
examples = [["ntpd", "sysinit.target"]]
common = true
description = """\
The list of units names to monitor. \
If empty or not present, all units are accepted. \
Unit names lacking a `"."` will have `".service"` appended to make them a valid service unit name.\
"""