[sources.syslog]
delivery_guarantee = "best_effort"
guides = []
output_types = ["log"]
resources = []
through_description = "the Syslog 5424 protocol"

[sources.syslog.fields.appname]
type = "string"
description = """\
The appname extracted from the [Syslog 5424][urls.syslog_5424] line. If a \
appname is not found, then the key will not be added.
"""

[sources.syslog.fields.host]
type = "string"
key_name_option = "host_key"
description = """\
The hostname extracted from the [Syslog 5424][urls.syslog_5424] line. If a \
hostname is not found, then Vector will use the upstream host IP address.\
"""

[sources.syslog.fields.facility]
type = "string"
description = """\
The facility extracted from the [Syslog 5424][urls.syslog_5424] line. If a \
facility is not found, then the key will not be added.
"""

[sources.syslog.fields.msgid]
type = "string"
description = """\
The msgid extracted from the [Syslog 5424][urls.syslog_5424] line. If a \
msgid is not found, then the key will not be added.
"""

[sources.syslog.fields.procid]
type = "string"
description = """\
The procid extracted from the [Syslog 5424][urls.syslog_5424] line. If a \
procid is not found, then the key will not be added.
"""

[sources.syslog.fields.severity]
type = "string"
description = """\
The severity extracted from the [Syslog 5424][urls.syslog_5424] line. If a \
severity is not found, then the key will not be added.
"""

[sources.syslog.fields.timestamp]
type = "timestamp"
description = """\
The timestamp extracted from the incoming line. If a timestamp is not found, \
then Vector will use the current time.\
"""

[sources.syslog.fields.version]
type = "string"
description = """\
The version extracted from the [Syslog 5424][urls.syslog_5424] line. If a \
version is not found, then the key will not be added.
"""

[sources.syslog.options.address]
type = "string"
examples = ["0.0.0.0:9000", "systemd", "systemd#2"]
null = true
relevant_when = {mode = ["tcp", "udp"]}
common = true
description = """\
The TCP or UDP address to listen for connections on, or "systemd#N" to use \
the Nth socket passed by systemd socket activation. \
"""

[sources.syslog.options.host_key]
name = "host_key"
type = "string"
category = "Context"
null = false
default = "host"
section = "context"
description = """\
The key name added to each event representing the current host.\
"""

[sources.syslog.options.max_length]
type = "int"
default = 102400
null = true
unit = "bytes"
description = """\
The maximum bytes size of incoming messages before they are discarded.\
"""

[sources.syslog.options.mode]
type = "string"
null = false
description = "The input mode."

[sources.syslog.options.mode.enum]
tcp = "Read incoming Syslog data over the TCP protocol."
udp = "Read incoming Syslog data over the UDP protocol."
unix = "Read uncoming Syslog data through a Unix socker."

[sources.syslog.options.path]
type = "string"
examples = ["/path/to/socket"]
null = true
relevant_when = {mode = "unix"}
common = true
description = """\
The unix socket path. *This should be absolute path.*
"""